required = [
"github.com/hashicorp/errwrap",
"github.com/buger/goterm",
"github.com/fatih/structs",
"github.com/go-errors/errors",
"github.com/hashicorp/go-multierror",
"github.com/hashicorp/go-version",
"github.com/kardianos/osext",
"github.com/koding/multiconfig",
"github.com/mattn/go-colorable",
"gopkg.in/inconshreveable/log15.v2",
#"gopkg.in/inconshreveable/log15.v2_ild/stack",
]

[[constraint]]
  name = "github.com/elastifile/emanage-go"
  branch = "renana/_unified_emanage_client"

#[[constraint]]
#  branch = "master"
#  name = "github.com/golang/glog"

# CSI spec version
[[constraint]]
  name = "github.com/container-storage-interface/spec"
  version = "~1.1.0"

#[[override]]
#  name = "k8s.io/kubernetes"
#  version = "v1.13"
#
#[[override]]
#  name = "k8s.io/api"
#  version = "kubernetes-1.13.0-beta.2"
#
#[[override]]
#  name = "k8s.io/apimachinery"
#  version = "kubernetes-1.13.0-beta.2"
#
#[[override]]
#  name = "k8s.io/csi-api"
#  version = "kubernetes-1.13.0-beta.2"
#
#[[override]]
#  name = "k8s.io/client-go"
#  version = "kubernetes-1.13.0-beta.2"

#[[override]]
#  name = "k8s.io/kubernetes"
#  version = "v1.11"
#
#[[override]]
#  name = "k8s.io/api"
#  version = "kubernetes-1.11.0"
#
#[[override]]
#  name = "k8s.io/apimachinery"
#  version = "kubernetes-1.11.0"
#
#[[override]]
#  name = "k8s.io/csi-api"
#  version = "kubernetes-1.11.0"
#
#[[override]]
#  name = "k8s.io/client-go"
#  version = "kubernetes-1.11.0"
#
#

[[constraint]]
  name = "github.com/kubernetes-csi/drivers"
  version = "1.0.2"
