#[[constraint]]
#  name = "github.com/elastifile/emanage-go"
#  branch = "v3"

[[constraint]]
  name = "k8s.io/client-go"
  version = "7.0.0"

[[override]]
  name = "github.com/davecgh/go-spew"

[[override]]
  name = "github.com/go-stack/stack"

[[constraint]]
  name = "github.com/container-storage-interface/spec"
  version = "~0.3.0"

[[constraint]]
  name = "github.com/kubernetes-csi/drivers"
  revision = "d8f283cd941f1e24e20e62653476a3722633f43e"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "v1.13.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "v1.11.1"

[[override]]
  name = "k8s.io/api"

[[override]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[override]]
  revision = "5db89f0ca68677abc5eefce8f2a0a772c98ba52d"
  name = "github.com/docker/distribution"
