#[[constraint]]
#  name = "github.com/elastifile/emanage-go"
#  branch = "v3"

#[[constraint]]
#  branch = "master"
#  name = "github.com/golang/glog"



#[[override]]
#  name = "k8s.io/kubernetes"
#  version = "v1.13"
#
#[[override]]
#  name = "k8s.io/api"
#  version = "kubernetes-1.13.0-beta.2"
#
#[[override]]
#  name = "k8s.io/apimachinery"
#  version = "kubernetes-1.13.0-beta.2"
#
#[[override]]
#  name = "k8s.io/csi-api"
#  version = "kubernetes-1.13.0-beta.2"
#
#[[override]]
#  name = "k8s.io/client-go"
#  version = "kubernetes-1.13.0-beta.2"

[[override]]
  name = "k8s.io/kubernetes"
  version = "v1.11"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/csi-api"
  version = "kubernetes-1.11.0"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.11.0"
