kind: Service
apiVersion: v1
metadata:
  name: csi-ecfsplugin-attacher
  labels:
    app: csi-ecfsplugin-attacher
spec:
  selector:
    app: csi-ecfsplugin-attacher

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-ecfsplugin-attacher
spec:
  serviceName: "csi-ecfsplugin-attacher"
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-ecfsplugin-attacher
    spec:
      serviceAccount: csi-attacher
      containers:
        - name: csi-ecfsplugin-attacher
          image: gcr.io/gke-release/csi-attacher:v1.0.1-gke.0
          args:
            - "--v=10"
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins/csi-ecfsplugin/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/kubelet/plugins/csi-ecfsplugin
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi-ecfsplugin
            type: DirectoryOrCreate
