# NOTE: The service account `default:default` already exists in k8s cluster.
# You can create a new account by usiong the following manifest:
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-sa-rbac
subjects:
  - kind: ServiceAccount
    # References the ServiceAccount's `metadata.name`
    name: cluster-admin-sa
    # References the ServiceAccount's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

