/*
 * Elastifile FaaS API
 *
 * Elastifile Filesystem as a Service API
 *
 * OpenAPI spec version: 1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package efaasapi

type Deprecated struct {

	// Service Class state, DEPRECATED, OBSOLETE or DELETED, Deprecated indicate that service class was replaced by a newer one, but can be used for new/existing instances. Obsolete indicate in use by existing instances but will fail for new instances. Deleted indicate can not be used by either existing nor new created instances.
	State string `json:"state,omitempty"`

	// New service class that is in use instead
	Replacement string `json:"replacement,omitempty"`
}
