/*
 * Elastifile FaaS API
 *
 * Elastifile Filesystem as a Service API
 *
 * OpenAPI spec version: 1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package efaasapi

type EditParallel struct {
	SetCapacity SetCapacity `json:"setCapacity,omitempty"`

	SetScheduling Snapshots `json:"setScheduling,omitempty"`

	SetAccessors Accessors `json:"setAccessors,omitempty"`
}
