/*
 * Elastifile FaaS API
 *
 * Elastifile Filesystem as a Service API
 *
 * OpenAPI spec version: 1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package efaasapi

type Login struct {

	// [Output Only] session token to be passed by client with every following request.
	SessionToken string `json:"session_token,omitempty"`
}
