/*
 * Elastifile FaaS API
 *
 * Elastifile Filesystem as a Service API
 *
 * OpenAPI spec version: 1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package efaasapi

type ServiceProtection struct {

	// Defines the Availability Zones support
	ProtectionMode string `json:"protectionMode,omitempty"`

	// Number of data copies
	ReplicationLevel int32 `json:"replicationLevel,omitempty"`
}
