/*
 * Elastifile FaaS API
 *
 * Elastifile Filesystem as a Service API
 *
 * OpenAPI spec version: 1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package efaasapi

type SnapshotShareCreate struct {

	// [Output Only] Share name
	ShareName string `json:"shareName"`
}
