/*
 * Elastifile FaaS API
 *
 * Elastifile Filesystem as a Service API
 *
 * OpenAPI spec version: 1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package efaasapi

type Users struct {

	// List of users allowed to access resources on the specified project.
	Users []AllowedUser `json:"users"`
}
