/*
 * Elastifile FaaS API
 *
 * Elastifile Filesystem as a Service API
 *
 * OpenAPI spec version: 1.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package efaasapi

type Utilization struct {

	// The amount of data placed into the filesystem in bytes, without snapshots.
	FileSystem int32 `json:"fileSystem,omitempty"`

	// The amount of object store bytes taken for snapshots.
	Snapshots int32 `json:"snapshots,omitempty"`
}
