apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job
spec:
  template:
    spec:
      containers:
        - name: container1
          image: alpine
          volumeMounts:
            - name: volume1
              mountPath: /mnt
          command: ["dd", "if=/dev/zero", "of=/mnt/demofile", "bs=1M", "count=1000"]
      volumes:
        - name: volume1
          persistentVolumeClaim:
            claimName: demo-pvc
            readOnly: false
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
