apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:

      storage: 55Gi
  storageClassName: elastifile
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
   - name: container1
     image: alpine
     # imagePullPolicy: Always
     volumeMounts:
       - name: volume1
         mountPath: /mnt
     command: ["dd"]
     args: ["if=/dev/zero", "of=/mnt/ddfile", "bs=1M", "count=1000000"]
#     command: ["tail"]
#     args: ["-f", "/dev/null"]
  volumes:
   - name: volume1
     persistentVolumeClaim:
       claimName: demo-pvc
       readOnly: false
  restartPolicy: Never

