apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
   - name: container1
     image: alpine
     volumeMounts:
       - name: volume1
         mountPath: /mnt
     command: ["rm"]
     args: ["/mnt/ddfile"]
  volumes:
   - name: volume1
     persistentVolumeClaim:
       claimName: demo-pvc
       readOnly: false
  restartPolicy: Never
