apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
   - name: container1
     image: busybox
     volumeMounts:
       - name: volume1
         mountPath: /mnt
  volumes:
   - name: volume1
     persistentVolumeClaim:
       claimName: demo-pvc
       readOnly: false

