apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
   - name: container1
     image: alpine
     volumeMounts:
       - name: volume1
         mountPath: /mnt
     command: ["dd"]
     args: ["if=/dev/zero", "of=/mnt/demofile", "bs=1M", "count=1000000"]
  volumes:
   - name: volume1
     persistentVolumeClaim:
       claimName: demo-pvc
       readOnly: false
  restartPolicy: Never
