apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
   - name: web-server
     image: nginx
     volumeMounts:
       - name: volume1
         mountPath: /var/lib/www
  terminationGracePeriodSeconds: 30
  volumes:
   - name: volume1
     persistentVolumeClaim:
       claimName: demo-pvc
       readOnly: false

