apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-restore-pvc
spec:
  dataSource:
    name: demo-snap
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: elastifile
