apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: elastifile
parameters:
  UserMapping: remap_root

# no_mapping, remap_root, remap_all
