apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: demo-snap
spec:
  snapshotClassName: csi-ecfs-snapclass
  source:
    name: demo-pvc
    kind: PersistentVolumeClaim
