/* 
 * Elastifile FaaS API
 *
 * Elastifile Filesystem as a Service API
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package EfaasApi

type ClearTier struct {

	// Modi/Adi need to provide'
	Extension int32 `json:"extension"`

	// Modi/Adi need to provide'
	Balance int32 `json:"balance"`
}
