/* 
 * Elastifile FaaS API
 *
 * Elastifile Filesystem as a Service API
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package EfaasApi

type Instances struct {

	// [Output Only] The unique identifier for the resource. This identifier is defined by the server.
	Id string `json:"id,omitempty"`

	// The name of the resource, provided by the client when initially creating the resource. The resource name must be 1-63 characters long, and comply with RFC1035
	Name string `json:"name"`

	// [Output Only] A textual description of the resource.
	Description string `json:"description,omitempty"`

	// ServiceClass name
	ServiceClass string `json:"serviceClass"`

	// ServiceClass resource unique id
	ServiceClassId string `json:"serviceClassId,omitempty"`

	// ServiceClass descriptive name
	ServiceClassDescription string `json:"serviceClassDescription,omitempty"`

	// The number of storage capacity units provisioned
	ProvisionedCapacityUnits float32 `json:"provisionedCapacityUnits"`

	// The unit used for capacity, possible values are: Steps, Bytes.  Default value is Steps.
	CapacityUnitType string `json:"capacityUnitType,omitempty"`

	// The allocated capacity in bytes
	AllocatedCapacity int64 `json:"allocatedCapacity,omitempty"`

	// Region name for this request, required if serviceClass.serviceProtection.protectionMode is set to 'multi'.
	Region string `json:"region,omitempty"`

	// Zone name for this request, required if serviceClass.serviceProtection.protectionMode is set to 'single'.
	Zone string `json:"zone,omitempty"`

	// Name of your VPC network connected with service producer network.
	Network string `json:"network"`

	// The host project id if using a shared VPC network.
	NetworkProject string `json:"networkProject,omitempty"`

	Filesystems []DataContainer `json:"filesystems,omitempty"`

	// [Output Only] The status of the operation, which can be one of the following: PENDING, RUNNING, or DONE.
	Status string `json:"status,omitempty"`

	// [Output Only] An optional textual description of the current status of the operation.
	StatusMessage string `json:"statusMessage,omitempty"`

	// [Output Only] Creation timestamp in RFC3339 text format.
	CreationTimestamp string `json:"creationTimestamp,omitempty"`

	// [Output Only] Update timestamp in RFC3339 text format.
	UpdateTimestamp string `json:"updateTimestamp,omitempty"`

	// instance utilization metrics
	Utilization Utilization `json:"utilization,omitempty"`

	// instance health metrics
	ServiceHealth ServiceHealth `json:"serviceHealth,omitempty"`
}
