/* 
 * Elastifile FaaS API
 *
 * Elastifile Filesystem as a Service API
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package EfaasApi

type ServiceHealth struct {

	// The instance health
	State string `json:"state,omitempty"`

	// The instance health description
	Description string `json:"description,omitempty"`
}
