/* 
 * Elastifile FaaS API
 *
 * Elastifile Filesystem as a Service API
 *
 * OpenAPI spec version: 2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package EfaasApi

type StoragePrice struct {

	// Price per GB of the primary file system ($/GB/Mo)
	FilesystemStoragePrice float32 `json:"filesystemStoragePrice"`

	// Price per GB of ClearTier (Object) storage $/GB/Mo
	SnapshotsStoragePrice float32 `json:"SnapshotsStoragePrice"`

	Estimates interface{} `json:"estimates,omitempty"`
}
