apiVersion: v1
kind: Pod
metadata:
  name: demo-clone-pod
spec:
  containers:
   - name: container1
     image: alpine
     volumeMounts:
       - name: volume1
         mountPath: /mnt
     command: ["dd", "if=/mnt/demofile", "of=/dev/null", "bs=1M", "count=10",
               "&&", "dd", "if=/dev/null", "of=/mnt/demofile2", "bs=1M", "count=10"]
  volumes:
   - name: volume1
     persistentVolumeClaim:
       claimName: demo-clone-pvc
       readOnly: false
  restartPolicy: Never
  terminationGracePeriodSeconds: 30
